name: Tim Reichelt
favicon: null
layout_spectrum: 0.34959265124052763
typography_spectrum: 0.42851
title: Tim Reichelt - Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eb5eeb'
    - '#8ee500'
    - '#f9ccc6'
    - '#c2a794'
    - '#9d3fdf'
  brandStrength: 0.5
  lightness: 0.8681168935727328
  saturation: 0.5
  rhythmicContrast: 0.4167193111497909
purpose: []
